# Generated by Django 4.2.5 on 2023-09-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('program_type', models.CharField(choices=[('1', 'ONE_ON_ONE'), ('S', 'SMALL_GROUP'), ('C', 'CLASSROOM')], max_length=1)),
            ],
        ),
    ]
