# Generated by Django 4.2.5 on 2023-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonnote',
            name='homework_notes',
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='homework_accuracy_level',
            field=models.CharField(default='100%', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='homework_completion_level',
            field=models.CharField(choices=[('None', 'NONE'), ('Less than 50%', 'SOME'), ('50%', 'HALF'), ('Greater than 50%', 'MOST'), ('100%', 'ALL')], default='100%', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='homework_review_comments',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='lesson_comments',
            field=models.TextField(max_length=250),
        ),
    ]
