# Generated by Django 4.2.5 on 2023-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_student_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pronouns',
            field=models.CharField(default='Prefer not to answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='program_type',
            field=models.CharField(choices=[('1-on-1', 'TUTORING'), ('Small Group', 'GROUP'), ('Classroom', 'CLASS')], max_length=15),
        ),
    ]
