# Generated by Django 4.2.5 on 2023-09-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_lessonnote_lesson_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonnote',
            name='lesson_summary',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
